# Generated by Django 2.2.6 on 2019-10-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_auto_20191017_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_score',
            new_name='score',
        ),
    ]
