# Generated by Django 2.2.6 on 2019-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0004_auto_20191017_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Joker', max_length=60),
            preserve_default=False,
        ),
    ]
